[workspace]
git_release_name = "{{ package }}-{{ version }}"
git_tag_name = "{{ package }}-{{ version }}"
pr_labels = ["release", "bot"]
publish_timeout = "10m"

# Only try to publish releases when a release PR is merged
release_always = false

[changelog]
protect_breaking_commits = true
