# samd11 is a Cortex-M0 and thus thumbv6m

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = 'probe-run --chip ATSAMD11C14A'
rustflags = [
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",

   # To use defmt, the linker needs to be provided with this argument.  The BSP
   # uses build.rs to supply it conditionally, or uncomment this line to use it
   # unconditionally.
   # "-C", "link-arg=-Tdefmt.x",

  "-C", "link-arg=-Tlink.x",
]
