# vim:ft=toml:
[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip ATSAMD51J19A --speed 20000'

[build]
target = "thumbv7em-none-eabihf"
rustflags = [

   # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
   # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
   "-C", "link-arg=--nmagic",
   "-C", "link-arg=-Tdefmt.x", # uncomment if using defmt
   "-C", "link-arg=-Tlink.x",
]
