# The SDHC0 peripheral on some devices contains reset values for certain fields
# that are wider than their corresponding storage. Replace the invalid values
# with the ones from the datasheet.
SDHC0:
  _modify:
    HC1R:
        resetValue: 0x00
    HC1R_EMMC_MODE:
        resetValue: 0x00
    SISR:
        resetValue: 0x0000
