name: Bump PAC versions
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump (patch/minor/major)'
        required: true
        default: 'minor'
      sync_hal:
        description: 'Update PAC deps in HAL (yes/no)'
        required: true
        default: 'yes'

jobs:
  bump-pac-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - name: Bump PAC versions
        shell: bash
        run: |
          set -ex
          cargo install cargo-workspace2

          # Create a fake workspace file for all PACs.
          echo "[workspace]" > Cargo.toml
          echo "members = [" >> Cargo.toml
          for d in pac/*/ ; do echo "    \"${d::-1}\"," >> Cargo.toml; done
          echo "]" >> Cargo.toml
          echo "" >> Cargo.toml

          # Create a ws2 query string for all PACs.
          pacs=$(for d in pac/*/ ; do echo -n "${d:4:${#d}-5} "; done )
          pacs=${pacs::-1} # Trim trailing space

          echo "y" | cargo ws2 [ "${pacs}" ] publish ${{ github.event.inputs.bump }}

          rm Cargo.toml
          git diff > bump.patch

      - name: Update HAL deps
        if: github.event.inputs.sync_hal == 'yes'
        uses: ./.github/actions/sync-pac-versions

      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: bump.patch
          path: bump.patch

      - name: Cleanup
        shell: bash
        run: |
          set -ex
          rm bump.patch

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ATSAMD_BOT }}
          commit-message: ${{ github.event.inputs.bump }} bump of PAC versions
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: bump-pac
          delete-branch: true
          title: '[atsamd-bot] Bump PAC versions'
          body: |
            Automated `${{ github.event.inputs.bump }}` bump of all PAC versions.
            - Generated by `${{ github.actor }}`
            - Workflow: [bump-pac.yml][1]

            [1]: https://github.com/atsamd-rs/atsamd/tree/master/.github/workflows
          labels: |
            pac
            automated pr
            pac-version-bump
          draft: false
