name: Bump crate versions
on:
  workflow_dispatch:
    inputs:
      pac_bump:
        description: 'PAC version bump (none/patch/minor/major)'
        required: true
        default: 'none'
      sync_hal:
        description: 'Update PAC dep string in HAL crate (yes/no)'
        required: true
        default: 'yes'
      hal_bump:
        description: 'HAL version bump (none/patch/minor/major)'
        required: true
        default: 'none'
      sync_bsp:
        description: 'Update HAL dep string in T1 BSP crates (yes/no)'
        required: true
        default: 'yes'
      bsp_bump:
        description: 'T1 BSP version bump (none/patch/minor/major)'
        required: true
        default: 'none'

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        run: |
          sudo apt-get install python3-pip && pip install tomlkit
          rustup set profile minimal
          rustup override set stable
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ATSAMD_BOT_SSH_PRIVKEY }}
      - name: Setup
        shell: bash
        run: |
          set -ex
          cargo install cargo-edit

      - name: Bump PAC versions
        if: github.event.inputs.pac_bump != 'none'
        shell: bash
        run: |
          set -ex

          for dir in pac/*/ ; do
            # Remove the trailing slash
            dir=${dir%/}
            manifest="$dir/Cargo.toml"

            # Bump the PAC version
            cargo set-version --manifest-path $manifest --bump ${{ github.event.inputs.pac_bump }}

            # Update the changelog
            python3 .github/workflows/update_changelog.py $dir
          done

      - name: Update HAL deps
        if: github.event.inputs.sync_hal == 'yes'
        uses: ./.github/actions/sync-pac-versions

      - name: Bump HAL version
        if: github.event.inputs.hal_bump != 'none'
        shell: bash
        run: |
          set -ex

          # Bump the HAL version
          cargo set-version --manifest-path "hal/Cargo.toml" --exclude atsamd-hal-macros --bump ${{ github.event.inputs.hal_bump }}

          # Update the changelog
          python3 .github/workflows/update_changelog.py hal/

      - name: Update BSP deps
        if: github.event.inputs.sync_bsp == 'yes'
        uses: ./.github/actions/sync-bsp-versions

      - name: Bump BSP versions
        if: github.event.inputs.bsp_bump != 'none'
        shell: bash
        run: |
          set -ex

          jq -r '.boards | to_entries | map(select(.value.tier == 1) | .key) | .[]' crates.json | while read dir; do
            manifest="boards/$dir/Cargo.toml"

            # Bump the BSP version
            cargo set-version --manifest-path $manifest --bump ${{ github.event.inputs.bsp_bump }}

            # Update the changelog
            python3 .github/workflows/update_changelog.py "boards/$dir/"
          done

      - name: Generate patch
        shell: bash
        run: |
          git diff > bump.patch

      - name: Upload diff
        uses: actions/upload-artifact@v4
        with:
          name: bump.patch
          path: bump.patch

      - name: Cleanup
        shell: bash
        run: |
          set -ex
          rm bump.patch

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: |
            Bump crate versions

            HAL:  ${{ github.event.inputs.hal_bump }}
            Tier 1 BSPs:  ${{ github.event.inputs.bsp_bump }}
            PACs:  ${{ github.event.inputs.pac_bump }}
          committer: GitHub <noreply@github.com>
          author: atsamd-bot <atsamd-bot@users.noreply.github.com>
          signoff: false
          branch: bump-versions
          delete-branch: true
          title: '[atsamd-bot] Bump crate versions'
          body: |
            Automated bump of crate versions.
            - Workflow launched by `${{ github.actor }}`
            - Workflow: [bump-crates.yml][1]
            - PAC bump = `${{ github.event.inputs.pac_bump }}`
            - HAL bump = `${{ github.event.inputs.hal_bump }}`
            - BSP bump = `${{ github.event.inputs.bsp_bump }}`

            [1]: https://github.com/atsamd-rs/atsamd/tree/master/.github/workflows
          labels: |
            automated pr
            version-bump
          draft: false
