name: Release PAC crates
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches:
      - master

jobs:
  release-pacs:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'pac-version-bump'))
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2

      - name: Login
        run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Release PAC crates
        shell: bash
        run: |
          set -ex
          cargo install cargo-workspace2

          # Run `cargo publish` on each PAC.
          for d in pac/*/
          do
            (cd "${d}" && cargo publish );
          done
