name: Rust Formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup override set nightly
          rustup component add rustfmt
      - name: Rustfmt
        run: ./rustfmt.sh
